name: GET UP

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'weather message'
        required: false

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: GET UP
        run: |
          source venv/bin/activate
          python get_up.py ${{ secrets.G_T }} ${{ github.repository }} --weather_message ": ${{ github.event.inputs.message }}" --wc_robot_url ${{secrets.WC_ROBOT}}
