name: Replace README

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: false
  issue_comment:
    types: [created, edited]

env:
  GITHUB_NAME: mengziin
  GITHUB_EMAIL: chenyumeng6@gmail.com

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Replace README
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.G_T }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}' --issue_label_name '${{ github.event.issue.labels[0].name }}' 
        
      # Fix for the unsafe repo error: https://github.com/repo-sync/pull-request/issues/84
      - name: Run safe dir
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Push README
        run: |
          git config --local user.name mengziin
          git config --local user.email chenyumeng6@gmail.com
          git add .
          git commit -m "generated readme" || echo "no need to commit "
          git push || echo "no file change"
