name: Get Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,13 * * *"

env:
  GITHUB_NAME: mengziin
  GITHUB_EMAIL: chenyumeng6@gmail.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # python main.py ${{ secrets.G_T }} ${{ github.repository }} for gitblog TODO refator later
      - name: Generate new daily
        run: |
          source venv/bin/activate
          python get_daily.py ${{ secrets.G_T }} ${{ github.repository }}
          python main.py ${{ secrets.G_T }} ${{ github.repository }} 

      # Fix for the unsafe repo error: https://github.com/repo-sync/pull-request/issues/84
      - name: Run safe dir
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Push README
        run: |
          git config --local user.name mengziin
          git config --local user.email chenyumeng6@gmail.com
          git add .
          git commit -m "new daily stats" || echo "no file change"
          git push || echo "no need push"

